### ISSUE TITLE
site wrapper is not responsive

### ISSUE THREAD

**Issue by miorogvall** [bombsimon/det-blev-ingen-cd.com#2]
The wrapper that holds the content on the site seems to be set to have a fixed width, not allowing mobile users to take full advantage of the site features. Changing this to a responsive layout would enhance the user experience.

**Comment by karlmacklin** [comment]
I've experienced this issue too

**Comment by bombsimon** [comment]
@miorogvall: I've merged some changes based on other issues, all I did regarding this was to add the tag `<meta name="viewport" content="width=550">`. This makes the screen on my phone and table act as a 550px screen so the image and text fills the whole screen.

Is this good enough for this issue or did you have something else in mind?

PRs are welcome if you've got better ideas. :)

**Comment by bombsimon** [comment]
@miorogvall: I'll close this due to lack of response, please add a comment (or PR) if you're not satisfied.
