### ISSUE TITLE
Bad quality on site image

### ISSUE THREAD

**Issue by karlmacklin** [bombsimon/det-blev-ingen-cd.com#3]
The jpeg image on the site is very low quality, making it hard to read the contents.
Perhaps some image editing software could help with cleaning up that a bit? Or find some other way to solve that.

**Comment by bombsimon** [comment]
This is correct, the image has very bad quality. The reason the text is added below the picture is for this exact reason, to be able to read the text. After you suggested I switched to `figure` with `figcaption` after closing #4.

I don't think I'm the right person to fix the image with editing software. I tried to run it through some (free) jpeg enhancement tools but nothing really blew my mind.

Submissions to fix this are welcome but I don't think I'll give this a try anytime soon.

**Comment by bombsimon** [comment]
Apparently there will be a [documentary](https://ng.se/artiklar/komiker-gor-dokumentar-om-det-blev-ingen-cd-killarna) about this article and the persons in it!

I asked the author on [Facebook](https://www.facebook.com/jonasstrandbergstandup/posts/2099237350367669?comment_id=2099305177027553) to provide a better version of the original image if found while creating the documentary. Let's cross our fingers!

Also, [here's](https://youtu.be/PHMH3GBJ3NE) the trailer for the documentary on YouTube!

**Comment by bombsimon** [comment]
Maybe this could be something? Found it in an article about the above mentioned documentary. I've actually reached out to the creator (again) regarding a scanned image and since I haven't heard the final word yet I'm not changing the image right now. Nice to see a high resolution version though!

![dbic](https://i.imgur.com/GBBenzf.jpg)

**Comment by bombsimon** [comment]
Haven't heard anything from the creator nor in this issue. I made a compromise and added an alternative version found at https://det-blev-ingen-cd.com/?hd=true. Closing this issue.

**Comment by karlmacklin** [comment]
I see this solution as sufficient.
